/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Penjualan;


import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dani
 */
public class HalamanPenjualan extends javax.swing.JInternalFrame {

    /**
     * Creates new form HalamanPenjualan
     */
    private DefaultTableModel table1;
    
    public HalamanPenjualan() {
        initComponents();
        rb_5km.setVisible(false);
        rb_5to15km.setVisible(false);
        rb_15km.setVisible(false);
        txt_harga.setText("0");
        txt_diskon.setText("0");
        txt_biayakirim.setText("0");
        txt_totalbayar.setText("0");
        txt_jml.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        combox_namabunga = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_jml = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_diskon = new javax.swing.JTextField();
        GambarBunga = new javax.swing.JPanel();
        Gambar = new javax.swing.JLabel();
        cb_kirim = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        txt_biayakirim = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_totalbayar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledata = new javax.swing.JTable();
        btn_proses = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        txt_ttlpendapatan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        rb_5km = new javax.swing.JRadioButton();
        rb_5to15km = new javax.swing.JRadioButton();
        rb_15km = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txt_ttlterjual = new javax.swing.JTextField();

        jLabel1.setText("DATA PENJUALAN BUNGA TOKO \" SEGAR \"");

        jLabel2.setText("Nama Bunga");

        combox_namabunga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==Pilih Bunga==", "Anggrek", "Mawar", "Sedap Malam" }));
        combox_namabunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combox_namabungaActionPerformed(evt);
            }
        });

        jLabel3.setText("Harga/Tangkai");

        txt_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hargaKeyReleased(evt);
            }
        });

        jLabel4.setText("Jumlah Beli");

        txt_jml.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jmlKeyReleased(evt);
            }
        });

        jLabel5.setText("Diskon");

        GambarBunga.setBackground(new java.awt.Color(153, 153, 153));
        GambarBunga.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout GambarBungaLayout = new javax.swing.GroupLayout(GambarBunga);
        GambarBunga.setLayout(GambarBungaLayout);
        GambarBungaLayout.setHorizontalGroup(
            GambarBungaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Gambar, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
        );
        GambarBungaLayout.setVerticalGroup(
            GambarBungaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Gambar, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        cb_kirim.setText("Kirim");
        cb_kirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_kirimActionPerformed(evt);
            }
        });

        jLabel6.setText("Biaya Kirim");

        txt_biayakirim.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txt_biayakirimInputMethodTextChanged(evt);
            }
        });
        txt_biayakirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_biayakirimKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Total Bayar");

        txt_totalbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalbayarActionPerformed(evt);
            }
        });

        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama bunga", "Harga/Tangkai", "Jumlah", "Diskon", "Jarak kirim", "Biaya Kirim", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabledata);

        btn_proses.setText("PROSES");
        btn_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prosesActionPerformed(evt);
            }
        });

        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Total Pendapatan");

        label9.setBackground(new java.awt.Color(255, 0, 51));
        label9.setForeground(new java.awt.Color(255, 0, 51));

        rb_5km.setText("< 5 KM");
        rb_5km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_5kmActionPerformed(evt);
            }
        });

        rb_5to15km.setText("5 - 15 KM");
        rb_5to15km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_5to15kmActionPerformed(evt);
            }
        });

        rb_15km.setText("> 15 KM");
        rb_15km.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_15kmActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Total Bunga Terjual");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(cb_kirim)
                            .addComponent(jLabel7))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_biayakirim, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(label9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_diskon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txt_jml, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txt_harga, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combox_namabunga, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GambarBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rb_5km)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_5to15km)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_15km)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_ttlterjual, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_ttlpendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_proses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 47, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel1)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(combox_namabunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_jml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_diskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_kirim)
                            .addComponent(rb_5km)
                            .addComponent(rb_5to15km)
                            .addComponent(rb_15km)))
                    .addComponent(GambarBunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_biayakirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_totalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_proses)
                        .addGap(18, 18, 18)
                        .addComponent(btn_hapus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_ttlterjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ttlpendapatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(192, 192, 192))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combox_namabungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combox_namabungaActionPerformed
        // TODO add your handling code here:
        if(combox_namabunga.getSelectedIndex()==1){
            txt_harga.setText("20000");
            ImageIcon gambar = new ImageIcon("src/Gambar/anggrek.jpg");
            Gambar.setIcon(gambar);
        } else if(combox_namabunga.getSelectedIndex()==2){
            txt_harga.setText("30000");
            ImageIcon gambar = new ImageIcon("src/Gambar/mawar.jpg");
            Gambar.setIcon(gambar);
        } else if(combox_namabunga.getSelectedIndex()==3){
            txt_harga.setText("40000");
            ImageIcon gambar = new ImageIcon("src/Gambar/sedap malam.jpg");
            Gambar.setIcon(gambar);
        } else{
            Gambar.setIcon(null);
            txt_harga.setText("0");
            txt_diskon.setText("0");
            txt_jml.setText("0");
            cb_kirim.setSelected(false);
            txt_totalbayar.setText("0");
            rb_5km.setVisible(false);
            rb_5to15km.setVisible(false);
            rb_15km.setVisible(false);
            txt_biayakirim.setText("0");
        }
        
    }//GEN-LAST:event_combox_namabungaActionPerformed

    private void txt_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hargaKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_hargaKeyReleased

    private void txt_jmlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jmlKeyReleased
        // TODO add your handling code here:
        int harga, diskon, jml, total, totalbayar, biayakirim;
        
        harga = Integer.parseInt(txt_harga.getText());
        jml = Integer.parseInt(txt_jml.getText());
       
        total = harga * jml;
        if(total >= 300000){
            diskon = (5 * total) / 100;
            txt_diskon.setText(""+diskon);
            label9.setText("");
        } else{
            txt_diskon.setText("0");
            label9.setText("Minimum pembelian diatas 300 ribu dapat diskon 5%");
        }
        diskon = Integer.parseInt(txt_diskon.getText());
        totalbayar = total - diskon;
        
        txt_totalbayar.setText(""+totalbayar);
        
        
        
    }//GEN-LAST:event_txt_jmlKeyReleased

    private void cb_kirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_kirimActionPerformed
        // TODO add your handling code here:
        if(cb_kirim.isSelected()==true){
           rb_5km.setVisible(true);
           rb_5to15km.setVisible(true);
           rb_15km.setVisible(true);
        } else{
           rb_5km.setVisible(false);
           rb_5to15km.setVisible(false);
           rb_15km.setVisible(false);
        }

    }//GEN-LAST:event_cb_kirimActionPerformed

    private void rb_5kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_5kmActionPerformed
        // TODO add your handling code here:
        int biayakirim, diskon, jml, hargabunga,total, totalbayar;
        if(cb_kirim.isSelected() == true && rb_5km.isSelected() == true){
           rb_5to15km.setEnabled(false);
           rb_15km.setEnabled(false);
           txt_biayakirim.setText("0");
        } else{
           rb_5to15km.setEnabled(true);
           rb_15km.setEnabled(true);
           txt_biayakirim.setText("0");
        }
        biayakirim = Integer.parseInt(txt_biayakirim.getText());
        diskon = Integer.parseInt(txt_diskon.getText());
        jml = Integer.parseInt(txt_jml.getText());
        hargabunga = Integer.parseInt(txt_harga.getText());
        total = Integer.parseInt(txt_totalbayar.getText());
        
        totalbayar = total + biayakirim;
        txt_totalbayar.setText(""+totalbayar);
        
        
    }//GEN-LAST:event_rb_5kmActionPerformed

    private void rb_5to15kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_5to15kmActionPerformed
        // TODO add your handling code here:
        int biayakirim, diskon, jml, hargabunga,total, totalbayar,total2, totalbayar2;
        if(cb_kirim.isSelected() == true && rb_5to15km.isSelected() == true){
           rb_5km.setEnabled(false);
           rb_15km.setEnabled(false);
           txt_biayakirim.setText("25000");
           biayakirim = Integer.parseInt(txt_biayakirim.getText());
           diskon = Integer.parseInt(txt_diskon.getText());
           jml = Integer.parseInt(txt_jml.getText());
           hargabunga = Integer.parseInt(txt_harga.getText());
           total = Integer.parseInt(txt_totalbayar.getText());
        
        totalbayar = total + biayakirim;
        txt_totalbayar.setText(""+totalbayar);
        } else{
           rb_5km.setEnabled(true);
           rb_15km.setEnabled(true);
           txt_biayakirim.setText("0");
           total2 = Integer.parseInt(txt_totalbayar.getText());
           totalbayar2 = total2 - 25000;
           txt_totalbayar.setText(""+totalbayar2);
        }
        
        
    }//GEN-LAST:event_rb_5to15kmActionPerformed

    private void rb_15kmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_15kmActionPerformed
        // TODO add your handling code here:
        int biayakirim, diskon, jml, hargabunga,total, totalbayar,total2, totalbayar2;
        if(cb_kirim.isSelected() == true && rb_15km.isSelected() == true){
           rb_5to15km.setEnabled(false);
           rb_5km.setEnabled(false);
           txt_biayakirim.setText("50000");
           biayakirim = Integer.parseInt(txt_biayakirim.getText());
           diskon = Integer.parseInt(txt_diskon.getText());
           jml = Integer.parseInt(txt_jml.getText());
           hargabunga = Integer.parseInt(txt_harga.getText());
           total = Integer.parseInt(txt_totalbayar.getText());
           
           totalbayar = total + biayakirim;
           txt_totalbayar.setText(""+totalbayar);
        } else{
           rb_5to15km.setEnabled(true);
           rb_5km.setEnabled(true);
           txt_biayakirim.setText("0");
           total2 = Integer.parseInt(txt_totalbayar.getText());
           totalbayar2 = total2 - 50000;
           txt_totalbayar.setText(""+totalbayar2);
        }
    }//GEN-LAST:event_rb_15kmActionPerformed

    private void txt_biayakirimInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txt_biayakirimInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_biayakirimInputMethodTextChanged

    private void txt_totalbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalbayarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_totalbayarActionPerformed

    private void txt_biayakirimKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_biayakirimKeyReleased
        // TODO add your handling code here:
        int biayakirim, total1, totalbayar;
        biayakirim = Integer.parseInt(txt_biayakirim.getText());
        totalbayar = Integer.parseInt(txt_totalbayar.getText());
        total1 = totalbayar + biayakirim;
        txt_totalbayar.setText(""+total1);
    }//GEN-LAST:event_txt_biayakirimKeyReleased

    private void btn_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prosesActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabledata.getModel();
        Object[] data = new Object[7];
        data[0] = combox_namabunga.getSelectedItem();
        data[1] = txt_harga.getText();
        data[2] = txt_jml.getText();
        data[3] = txt_diskon.getText();
        if(cb_kirim.isSelected()==true && rb_5km.isSelected() == true){
            data[4] = "5 KM";
        } else if(cb_kirim.isSelected() == true && rb_5to15km.isSelected() == true){
            data[4] = "5 - 15 KM";
        } else{
            data[4] = "15 KM";
        }
        //data[4] = rb_5km.getSelectedObjects();
        data[5] = txt_biayakirim.getText();
        data[6] = txt_totalbayar.getText();
        
        model.addRow(data);
        
        int totalbungaterjual = 0;
        int totalpendapatan = 0;
        for(int i = 0; i<tabledata.getRowCount(); i++){
            int jmlterjual = Integer.parseInt((String)tabledata.getValueAt(i, 2));
            int pendapatan = Integer.parseInt((String)tabledata.getValueAt(i, 6));
            totalbungaterjual += jmlterjual;
            totalpendapatan += pendapatan; 
        }
        txt_ttlterjual.setText(""+totalbungaterjual);
        txt_ttlpendapatan.setText(""+totalpendapatan);
    }//GEN-LAST:event_btn_prosesActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
         txt_harga.setText("0");
            txt_diskon.setText("0");
            txt_jml.setText("0");
            cb_kirim.setSelected(false);
            txt_totalbayar.setText("0");
            rb_5km.setVisible(false);
            rb_5to15km.setVisible(false);
            rb_15km.setVisible(false);
            txt_biayakirim.setText("0");
            rb_5km.setSelected(false);
            rb_5to15km.setSelected(false);
            rb_15km.setSelected(false);
            rb_5km.setEnabled(true);
            rb_5to15km.setEnabled(true);
            rb_15km.setEnabled(true);
            combox_namabunga.setSelectedIndex(0);
    }//GEN-LAST:event_btn_hapusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Gambar;
    private javax.swing.JPanel GambarBunga;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_proses;
    private javax.swing.JCheckBox cb_kirim;
    private javax.swing.JComboBox<String> combox_namabunga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label9;
    private javax.swing.JRadioButton rb_15km;
    private javax.swing.JRadioButton rb_5km;
    private javax.swing.JRadioButton rb_5to15km;
    private javax.swing.JTable tabledata;
    private javax.swing.JTextField txt_biayakirim;
    private javax.swing.JTextField txt_diskon;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jml;
    private javax.swing.JTextField txt_totalbayar;
    private javax.swing.JTextField txt_ttlpendapatan;
    private javax.swing.JTextField txt_ttlterjual;
    // End of variables declaration//GEN-END:variables
}
